### PR TITLE
Layout fixes

### PR DESCRIPTION
**Pull request by furedal**

### CODE REVIEW

**Comment by Dekker1** [comment]
I tested these changes today and there are some problems with the new configuration options. Although I understand the need to add the API keys, there are some other changes that do not work. the SQLite database offered us the option of easily running tests. The API keys you have in the development settings would be public, which I doubt would be a good idea (they should probably do in a `local.py` in the same directory, not committed to the repository, with maybe a guide of how to make them).

The production settings changing also means we need to change the configuration of the server. We need to add the API keys to the Ansible configuration.
It also seems like one of the API keys is missing in the production configuration.

**Comment by furedal** [comment]
I think I might have added those actual keys there by mistake, doesn't really matter very much as they are just test-keys created by me.

**Comment by Dekker1** [comment]
I'm wondering if those keys might not be better to be configured from the wagtail admin settings, instead of in the django settings files. They don't seem to be directly necessary during setup and might change.

**Comment by furedal** [comment]
Only thing i thinking about is that those values should mostly be private just as a username and password. Storing those in the database is not really a good idea.

**Comment by Dekker1** [comment]
We can do the same for the API keys, we might not be able to hash them again, but we can easily encrypt them using the secret key in configuration

**Comment by furedal** [comment]
Get your point. Do however you like, I feel like its a really small issue anyway.

**Pull request closed without merging**
