### PR TITLE
NTI-work inclusion

### PR DESCRIPTION
**Pull request by Marmingen**
### Description of the Change

Makes sure the work done by the NTI students gets merged

### CODE REVIEW

**Review by dakaza98 — CHANGES_REQUESTED** [review]
image
The translation "din ansökan har skickats in" is still wrong. In english it says "no applications has been sent in"

**Comment by dakaza98** [comment]
What will happen to existing footers on the website when the migration is done? I assume that for one of the languages they will be completely empty? Which language will the current footer be transferred to? I'm thinking it a manual migration will be needed or if website owners need to be informed about this change so that they can fix both versions. Although come to think of it, not all website owners might be using the footer or even have access to them

**Comment by Marmingen** [comment]
Going to add migration to make sure the footers are not empty + fix translation

**Review by Lofkvist — APPROVED** [review]

**Comment by Marmingen** [comment]
migration to copy data from the existing footer column is now in place

**Review by dakaza98 — APPROVED** [review]

**Pull request merged**
