### PR TITLE
Fix/fix instagram

### PR DESCRIPTION
**Pull request by dakaza98**
This PR creates a new block called instagram that displays the latest image/video from a selected instagram account. The process is a bit special so in the admin view there is a tab for instagram feeds. There you can add your instagram account (you must first accept it via the instagram authenticator. This returns a token which we convert to a short lived token which we convert to a long lived token (yeah, thanks facebook). The long lived token expires after 60 days so I have also added a cron job that updates those.

I have also changed the raven logging module to sentrys new logging module

### CODE REVIEW

**Comment by dakaza98** [comment]
What remains is to verify the UTN app on facebook so that we can start using the Instagram block in production

**Comment by dakaza98** [comment]
UPDATE: We have received our documents from skatteverket and are now waiting for facebook to approve us

**Comment by dakaza98** [comment]
Facebook has approved us! I will update this PR and check that everything is working

**Comment by dakaza98** [comment]
@Antonfogelberg This PR is ready to be merged now!

**Review by Antonfogelberg — APPROVED** [review]

**Pull request merged**
